### ISSUE TITLE
Tiny typo in Overview

### ISSUE THREAD

**Issue by mahSource** [odin-lang/odin-lang.org#145]
This could be grouped with the next editorial commit cleaning up small issues.
Under this header: <https://odin-lang.org/docs/overview/#cast-operator>
The following line should have the second 'is' changed to 'in':
```
This is useful is some contexts but has the same semantic meaning.
```
Suggest changing to:
```
This is useful in some contexts but has the same semantic meaning.
```

**Comment by Kelimion** [comment]
Fixed, thanks.
