### ISSUE TITLE
Compile-time array access bound checking statement should be corrected/updated

### ISSUE THREAD

**Issue by mahSource** [odin-lang/odin-lang.org#147]
In the Odin Overview in this section: <https://odin-lang.org/docs/overview/#fixed-arrays>
It states:
```
Array access is always bounds checked (at compile-time and at runtime). 
```
This is not true, it is not **always** checked.  For example the code below does not throw a compilation warning or compilation error; but thankfully does panic (error) during runtime.
```odin
myarray3 := [?]int{1, 2, 3, 4, 5, 6}
    for i in 0 ..= 6 {
        fmt.print(myarray3[i], "")
    }
```
Suggest to change Overview sentence to this or something similar:
```
Array access is bounds checked by default, both at compile-time (with constant indices) and at runtime.
```
Thanks to Sentient Coffee for the suggested wording tweak!

**Comment by Skytrias** [comment]
next time feel free to create a PR with all fixes combined 😄
