### ISSUE TITLE
RSS for /news

### ISSUE THREAD

**Issue by kuchta** [odin-lang/odin-lang.org#156]
Please add RSS for https://odin-lang.org/news so we can follow

**Comment by Kelimion** [comment]
Fixed in 26a05ee.

**Comment by kuchta** [comment]
@Kelimion Sorry, I haven't noticed since there is typo in:

```
<link rel="alternate" type="application/rss+xml" href="https://odin-lang.orgcategories/newsletter/index.xml" title="Odin Newsletter">
```

**Comment by Kelimion** [comment]
> @Kelimion Sorry, I haven't noticed since there is typo in:
> 
> ```
> <link rel="alternate" type="application/rss+xml" href="https://odin-lang.orgcategories/newsletter/index.xml" title="Odin Newsletter">
> ```

Fixed. It's because when you use `hugo server` locally, the site variable ends in `/` already, so you get `//categories`, which is why I removed the `/`.
