### ISSUE TITLE
Improve installation guide

### ISSUE THREAD

**Issue by babakfp** [odin-lang/odin-lang.org#194]
Hi 👋

I was here to write about adding a link and description for the [releases](https://github.com/odin-lang/Odin/releases/) page in the docs, I checked out the docs again and there was already a link to that page.

When I opened the installation page for the first time, I immediately searched for "Windows" without reading the starting section. So, I didn't know that there were easier ways to install it. I cloned, I didn't have Visual Studio installed, so I was going to download Visual Studio, but then I googled to see if there was an easier way to install it and that's when I saw a video that downloaded Odin from the releases page. I feel like this was my fault, however, I think the documentation can be improved to prevent such stories from happening again.

I'm not sure what could be the best solution, maybe adding a sentence to each build section, saying something like "You can download the build directly, or you can build it yourself by doing...".

**Comment by gingerBill** [comment]
https://odin-lang.org/docs/install/

What is unclear about these instructions? 

You have admitted to NOT reading any of the documentation and then complained it wasn't good enough?
