### ISSUE TITLE
add documentation about implicit allocation from assignment operator m[k] = v and use of context.allocator

### ISSUE THREAD

**Issue by yohn-kohl** [odin-lang/odin-lang.org#232]
please fix wording below to make clear and short, but you can look at this closed issue for more details
https://github.com/odin-lang/Odin/issues/4109

recommend
1. in the hashmap section of reference documents state that implicit dynamic allocation will happen from use of assignment **operator** anytime you add a k/v pair.  if map was declared without `make` where you could change default allocator with programmer **procedure** call then the default allocator is used and not a allocator you could set in `make` procedure that will be remembered by map....so if you change context.allocator for something else and add pairs to map initialized this way it will change allocators too.  documents should state this
2. note should be added to `make` section of documentation warning that it should be used if you want more explicit way to assign allocator to map struct for life of map, since it has explicit parameter and choice to pass argument for `allocator` and if you do not use make but declare map like said in 1 above that adding pairs will allocate automatically with no choice of `allocator` other than changing default context.allocator.
3. could add something in faq's to make it clear about maps and maybe dynamic array (tetralux said this might be the same behavior but i will look at that next since he said it) about 1 and 2 above.  I searched discord and there are many questions about this.
4. tetralux and others on discord had thoughts that this switch `-no-dynamic-literals` might protect against this but that is not the case for m[k] = v it does protect with compiler error for `x := map[string]int{ "hi" = 0 }` so there is confusion about this switch, but also this switch is not in the `odin help build` list of compiler, it should be documented there too since it is a useful switch but has nothing to do with 1, 2, or 3 above.

please fix words and terms above if they are not good, but i think you get the idea and can ask tetralux and gingerbill if this is not clear above, but this documents the issue

**Comment by gingerBill** [comment]
So this is just the same complaint but moved elsewhere. When I sent the link to this repo, I meant make a PR with the requested changes. Usually this is the better approach as it gives a clearer example of what people want, rather than us guessing.

**Comment by Kelimion** [comment]
None of us see any point in documenting that adding something to a hash map requires memory. It is self-evident. You clearly disagree, and believe it's not obvious and something people ought to look out for. If anyone is best placed to explain the lack of obviousness, it's you, not those who never considered this, so we've done you the courtesy of allowing you to write a pull request explaining the position, to - as you put it - improve the language and/or the documentation.

And _again_ you're coming up with reasons why others should do something to address your niche concern. English as a second language doesn't fly as an excuse here. Stop acting in bad faith.
