### ISSUE TITLE
[Request]: Add WinGet to Odin-Lang's Repology

### ISSUE THREAD

**Issue by og-mrk** [odin-lang/odin-lang.org#245]
A request to add `odin-lang.Odin` WinGet Package, found in `winget-pkgs` repo, which've been maintained for quite sometime by the writer of this Issue Ticket, so I kindly ask to project maintainers, or people with permission to Odin-Lang's Repology list, to add WinGet as another way of installing Odin on Windows.

> [!NOTE]
> The `odin-lang.Odin` Package installs the Stable Release of Odin, not the Nightly Builds.

If you've any concerns related to the WinGet package in question (`odin-lang.Odin`), or any suggestion that can improve it, then feel free to send it and I'll reply when I can 😄

**Comment by laytan** [comment]
We do not have any way of adding things to Repology.
Looking at Repology, they don't have WinGet at all, there may be some place you can ask them to add WinGet to their service.

**Comment by laytan** [comment]
Found an issue about adding WinGet here: https://github.com/repology/repology-updater/issues/1392
