### ISSUE TITLE
Add link to more examples

### ISSUE THREAD

**Issue by Apis035** [odin-lang/odin-lang.org#259]
The front page of Odin website provides 5 examples of Odin code (Hellope, Array Programming, SOA Types, ...). 

There are actually more [examples](https://github.com/odin-lang/examples) but to get to it you have to:
- Click GitHub button on top right.
- Click odin-lang on top left.
- Click on examples repository.

Suggest adding a button on the front page which leads to the examples repository. Something like this.
![image](https://github.com/user-attachments/assets/7258da96-7689-4d1b-8181-47662a67cd57)

**Comment by Skytrias** [comment]
Added in the recent commit [49193ba27b34540a0276be013b7c773a4d223bf2](https://github.com/odin-lang/odin-lang.org/commit/49193ba27b34540a0276be013b7c773a4d223bf2)

Thank you for the suggestion!
