### ISSUE TITLE
Missing semicolon in "if statement" docs

### ISSUE THREAD

**Issue by FutureMillennium** [odin-lang/odin-lang.org#41]
I believe I found an error in the Odin docs.

/content/docs/overview.md

Under "if statement", the second example is missing a semicolon in the condition. I tested this in Odin to make sure.

```
if x := foo() x < 0 {
    fmt.println("x is negative")
}
```

**Comment by zacharycarter** [comment]
This seems to have been addressed. I think this can be closed.
